apiVersion: v1
kind: Pod
metadata:
  name: sheel-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
  volumeMounts:
  - name: shared-data
    mountPath: /usar/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default